[package]
name = "crypto-market-multicast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
net2 = "0.2"
clap = "~2.27.0"
tokio = { version = "1.18.2", features = ["rt-multi-thread", "macros"] }
log = "0.4.17"


[dependencies.wmjtyd-libstock]
git = "https://github.com/wmjtyd/libstock.git"
default-features = false
features = ["crypto", "zeromq", "slack"]