[package]
name = "crypto-market-publisher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quiche = "0.14.0"
mio = { version = "0.8", features = ["net", "os-poll"] }
ring = "0.16"
lazy_static = "1"
log = { version = "0.4", features = ["std"] }
nanomsg = "0.7.2"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
url = "1"